# Desafio PLD — Nível 1: dados e primeira análise com LLM

Triagem de operações financeiras para **Prevenção à Lavagem de Dinheiro**.

- **Parte A** — tratamento de dados e regras determinísticas (pandas);
- **Parte B** — parecer interpretativo com LLM, em estrutura validada.

Princípio central do desenho: **cálculo é pandas; interpretação é LLM.**
Somar, medir mediana, contar e comparar com limite acontece aqui, deterministicamente.
O modelo só recebe números prontos e os interpreta.

In [1]:
import json
import time
from pathlib import Path
from typing import Literal

import pandas as pd
from pydantic import BaseModel, Field, ValidationError, field_validator

CAMINHO_DADOS = Path("../dados/dados_nivel_1.json")

bruto = json.loads(CAMINHO_DADOS.read_text(encoding="utf-8"))
taxa_cambio = float(bruto["taxa_cambio_usd_brl"])
df_bruto = pd.DataFrame(bruto["operacoes"])

print(f"Operações carregadas: {len(df_bruto)} | Clientes: {df_bruto['cliente_id'].nunique()}")
print(f"Taxa de câmbio fixa informada no próprio arquivo: USD 1,00 = BRL {taxa_cambio}")
df_bruto.head()

Operações carregadas: 20 | Clientes: 6
Taxa de câmbio fixa informada no próprio arquivo: USD 1,00 = BRL 5.4

,id,cliente_id,data,valor,moeda,canal,tipo,contraparte,observacao
0,OP-0001,CLI-A-1,2026-03-09,18100,BRL,pix,transferencia_enviada,Alfa Comercio LTDA,
1,OP-0002,CLI-A-1,2026-03-09,17300,BRL,pix,transferencia_enviada,Alfa Comercio LTDA,
2,OP-0003,CLI-A-1,2026-03-09,18800,BRL,ted,transferencia_enviada,Beta Servicos ME,
3,OP-0004,CLI-A-1,2026-03-21,3300,BRL,boleto,pagamento,Gama Distribuidora,
4,OP-0005,CLI-A-2,2026-03-14,25900,BRL,ted,transferencia_enviada,Delta Transportes,

## Parte A — Auditoria de qualidade dos dados

Antes de tratar, diagnosticar. O enunciado avisa que há problemas plantados — vamos encontrá-los sistematicamente.

In [2]:
print("== Auditoria de qualidade ==")

# --- IDs repetidos
dups_id = df_bruto[df_bruto.duplicated("id", keep=False)].sort_values("id")
print(f"\n[1] IDs duplicados: {dups_id['id'].unique().tolist()}")
if not dups_id.empty:
    copias_exatas = {i: (len(g.drop_duplicates()) == 1) for i, g in dups_id.groupby("id")}
    print("    As linhas com mesmo id sao copias identicas?", copias_exatas)
    display(dups_id[["id", "cliente_id", "data", "valor", "canal", "contraparte"]])

# --- Datas ausentes
sem_data = df_bruto[df_bruto["data"].isna()]
print(f"\n[2] Operacoes sem data: {sem_data['id'].tolist()}")
print("    Observacao registrada no legado:", sem_data["observacao"].unique().tolist())

# --- Moeda estrangeira
estrangeiras = df_bruto[df_bruto["moeda"] != "BRL"]
print("\n[3] Operacoes em moeda estrangeira:")
display(estrangeiras[["id", "cliente_id", "data", "valor", "moeda", "observacao"]])

# --- Sanidade geral
print("\n[4] Valores nao positivos:",
      df_bruto.loc[pd.to_numeric(df_bruto["valor"], errors="coerce") <= 0, "id"].tolist())
print("[5] Categorias de canal:", sorted(df_bruto["canal"].unique()))
print("[6] Categorias de tipo :", sorted(df_bruto["tipo"].unique()))
print("[7] Intervalo de datas :", df_bruto["data"].min(), "->", df_bruto["data"].max())

== Auditoria de qualidade ==

[1] IDs duplicados: ['OP-0007']
    As linhas com mesmo id sao copias identicas? {'OP-0007': True}

        id cliente_id        data  valor canal          contraparte
6  OP-0007    CLI-A-3  2026-03-05  17200   pix  Epsilon Consultoria
9  OP-0007    CLI-A-3  2026-03-05  17200   pix  Epsilon Consultoria

[2] Operacoes sem data: ['OP-0017']
    Observacao registrada no legado: ['data nao capturada pelo sistema']

[3] Operacoes em moeda estrangeira:

         id cliente_id        data  valor moeda             observacao
13  OP-0013    CLI-A-4  2026-03-24  12000   USD  remessa internacional

[4] Valores nao positivos: []
[5] Categorias de canal: ['boleto', 'cartao', 'especie', 'pix', 'ted']
[6] Categorias de tipo : ['deposito', 'pagamento', 'transferencia_enviada', 'transferencia_recebida']
[7] Intervalo de datas : 2026-03-03 -> 2026-03-28

### O que encontrei — e por que tratei assim

| # | Problema | Evidência | Decisão | Justificativa |
|---|----------|-----------|---------|---------------|
| 1 | **Registro duplicado** | `OP-0007` aparece 2× (cópias exatas — regravação do legado) | `drop_duplicates(subset="id")`, mantendo a 1ª | A duplicata **infla artificialmente** o dia 05/03 de CLI-A-3: com ela a soma dá R$ 65.700,00 e dispararia a Regra 1; o correto é R$ 48.500,00. Deduplicar evita falso positivo. |
| 2 | **Data ausente** | `OP-0017` com `data = null` e observação *"data nao capturada pelo sistema"* | Manter na base (marcada em `data_ausente`); **excluir apenas da Regra 1** | O valor existe e alimenta volume/mediana normalmente. Mas agrupá-la "por dia" exigiria inventar uma data — imputação criaria padrão falso. A Regra 2 não depende de data. |
| 3 | **Valor em USD** | `OP-0013` (US\$ 12.000, "remessa internacional") | Converter para BRL com a taxa fixa **antes de qualquer regra** | Se a Regra 2 rodasse sobre moedas misturadas, a mediana do cliente ficaria distorcida e o valor atípico **escaparia** (demonstrado na validação abaixo). |

Verificações que passaram limpas: nenhum valor negativo/zero, categorias de `canal` e `tipo` consistentes, datas dentro de março/2026.

In [3]:
# P1 — deduplicação por id (as duplicatas eram cópias exatas)
removidas = len(df_bruto) - len(df_bruto.drop_duplicates(subset="id"))
df = df_bruto.drop_duplicates(subset="id", keep="first").reset_index(drop=True)

# P2 — datas nulas marcadas (mantidas na base)
df["data"] = pd.to_datetime(df["data"], errors="coerce")
df["data_ausente"] = df["data"].isna()

# P3 — normalização monetária para BRL, ANTES de qualquer regra
fator = df["moeda"].map({"BRL": 1.0, "USD": taxa_cambio})
df["valor_brl"] = (df["valor"] * fator).round(2)

print(f"Duplicatas removidas: {removidas} | Base final: {len(df)} operações")
print("Operação afetada pela normalização:")
df.loc[df["moeda"] == "USD", ["id", "cliente_id", "valor", "moeda", "valor_brl"]]

Duplicatas removidas: 1 | Base final: 19 operações
Operação afetada pela normalização:

         id cliente_id  valor moeda  valor_brl
12  OP-0013    CLI-A-4  12000   USD    64800.0

## Agregações pedidas

In [4]:
volume_por_cliente = (
    df.groupby("cliente_id")["valor_brl"]
      .agg(volume_total_brl="sum", qtd_operacoes="count")
      .sort_values("volume_total_brl", ascending=False)
)
print("== Volume total transacionado por cliente (BRL) ==")
display(volume_por_cliente)

qtd_por_canal = (
    df.groupby("canal")["id"].count()
      .sort_values(ascending=False)
      .rename("qtd_operacoes")
      .to_frame()
)
print("== Quantidade de operações por canal ==")
qtd_por_canal

== Volume total transacionado por cliente (BRL) ==

            volume_total_brl  qtd_operacoes
cliente_id
CLI-A-4              79500.0              4
CLI-A-1              57500.0              4
CLI-A-2              52900.0              2
CLI-A-3              48500.0              3
CLI-A-5              16900.0              4
CLI-A-6              10200.0              2

== Quantidade de operações por canal ==

         qtd_operacoes
canal
pix                  8
ted                  5
boleto               3
cartao               2
especie              1

## Regras determinísticas

**Regra 1 — Fracionamento.** Sinalizar o cliente que, em um **mesmo dia**, realizou
**≥ 3 operações** cuja **soma > R$ 50.000,00**, sendo que **nenhuma operação isolada
atinge R$ 20.000,00**.

**Regra 2 — Valor atípico.** Sinalizar a operação cujo `valor_brl` seja
**superior a 5× a mediana** dos valores do mesmo cliente — aplicada somente a
clientes com **4 ou mais operações** (mediana instável em amostras pequenas).

As flags ficam por **operação** (`flag_fracionamento` marca todas as operações do
dia sinalizado; `flag_valor_atipico` marca a operação atípica).

In [5]:
def aplicar_regra_fracionamento(base: pd.DataFrame):
    """Marca operações pertencentes a (cliente, dia) com padrão de fracionamento."""
    base = base.copy()
    base["flag_fracionamento"] = False

    validos = base.loc[~base["data_ausente"]]          # sem data, não há "mesmo dia"
    resumo = (
        validos.groupby(["cliente_id", "data"])["valor_brl"]
               .agg(qtd_operacoes="count", soma_dia="sum", maior_op="max")
               .reset_index()
    )
    suspeitos = resumo[
        (resumo["qtd_operacoes"] >= 3)
        & (resumo["soma_dia"] > 50_000)
        & (resumo["maior_op"] < 20_000)
    ]
    if not suspeitos.empty:
        chaves = set(zip(suspeitos["cliente_id"], suspeitos["data"]))
        mascara = [
            (not ausente) and ((cli, dt) in chaves)
            for cli, dt, ausente in zip(base["cliente_id"], base["data"], base["data_ausente"])
        ]
        base.loc[mascara, "flag_fracionamento"] = True
    return base, suspeitos


df, dias_fracionamento = aplicar_regra_fracionamento(df)

print("Dias sinalizados pela Regra 1:")
display(dias_fracionamento.assign(data=dias_fracionamento["data"].dt.strftime("%Y-%m-%d")))

Dias sinalizados pela Regra 1:

  cliente_id        data  qtd_operacoes  soma_dia  maior_op
0    CLI-A-1  2026-03-09              3   54200.0   18800.0

In [6]:
def aplicar_regra_valor_atipico(base: pd.DataFrame) -> pd.DataFrame:
    """Marca operações cujo valor_brl > 5x a mediana do cliente (clientes com >= 4 ops)."""
    base = base.copy()
    base["flag_valor_atipico"] = False

    tamanho = base.groupby("cliente_id")["valor_brl"].transform("size")
    mediana_cli = base.groupby("cliente_id")["valor_brl"].transform("median")
    elegivel = tamanho >= 4
    base.loc[elegivel, "flag_valor_atipico"] = (
        base.loc[elegivel, "valor_brl"] > 5 * mediana_cli[elegivel]
    )
    return base


df = aplicar_regra_valor_atipico(df)

sinalizadas = df[df[["flag_fracionamento", "flag_valor_atipico"]].any(axis=1)].copy()
sinalizadas["data"] = sinalizadas["data"].dt.strftime("%Y-%m-%d").fillna("(sem data)")
print("Operações sinalizadas pelas duas regras:")
sinalizadas[["id", "cliente_id", "data", "valor_brl", "flag_fracionamento", "flag_valor_atipico"]]

Operações sinalizadas pelas duas regras:

,id,cliente_id,data,valor_brl,flag_fracionamento,flag_valor_atipico
0,OP-0001,CLI-A-1,2026-03-09,18100.0,True,False
1,OP-0002,CLI-A-1,2026-03-09,17300.0,True,False
2,OP-0003,CLI-A-1,2026-03-09,18800.0,True,False
12,OP-0013,CLI-A-4,2026-03-24,64800.0,False,True

## Validação das regras

Uma regra só vale se capturar o caso-alvo **e rejeitar o caso parecido** que não se enquadra.

In [7]:
def mostrar_dia(cliente: str, dia: str):
    recorte = df[(df["cliente_id"] == cliente) & (df["data"] == dia)]
    stats = dict(qtd=len(recorte),
                 soma=float(recorte["valor_brl"].sum()),
                 maior=float(recorte["valor_brl"].max()))
    dispara = stats["qtd"] >= 3 and stats["soma"] > 50_000 and stats["maior"] < 20_000
    return recorte, stats, bool(dispara)


print("** CASO POSITIVO — CLI-A-1 em 2026-03-09 deve ser CAPTURADO **")
_, st, disparou = mostrar_dia("CLI-A-1", "2026-03-09")
print(f"    {st} -> regra dispara? {disparou}  (esperado: True)")
assert disparou

print("\n-- CASO NEGATIVO 1 — CLI-A-3 em 2026-03-05: 3 ops, mas soma R$ 48.500 (< R$ 50 mil)")
_, st, disparou = mostrar_dia("CLI-A-3", "2026-03-05")
print(f"    {st} -> regra dispara? {disparou}  (esperado: False)")
assert not disparou
print("    Obs.: COM a duplicata OP-0007 a soma seria R$ 65.700 — a limpeza evitou o falso positivo.")

print("\n-- CASO NEGATIVO 2 — CLI-A-2 em 2026-03-14: soma R$ 52.900, mas só 2 ops e ambas >= R$ 20 mil")
_, st, disparou = mostrar_dia("CLI-A-2", "2026-03-14")
print(f"    {st} -> regra dispara? {disparou}  (esperado: False)")
assert not disparou
print("\nValidação da Regra 1: OK — captura o alvo e rejeita os dois quase-casos.")

** CASO POSITIVO — CLI-A-1 em 2026-03-09 deve ser CAPTURADO **
    {'qtd': 3, 'soma': 54200.0, 'maior': 18800.0} -> regra dispara? True  (esperado: True)

-- CASO NEGATIVO 1 — CLI-A-3 em 2026-03-05: 3 ops, mas soma R$ 48.500 (< R$ 50 mil)
    {'qtd': 3, 'soma': 48500.0, 'maior': 17200.0} -> regra dispara? False  (esperado: False)
    Obs.: COM a duplicata OP-0007 a soma seria R$ 65.700 — a limpeza evitou o falso positivo.

-- CASO NEGATIVO 2 — CLI-A-2 em 2026-03-14: soma R$ 52.900, mas só 2 ops e ambas >= R$ 20 mil
    {'qtd': 2, 'soma': 52900.0, 'maior': 27000.0} -> regra dispara? False  (esperado: False)

Validação da Regra 1: OK — captura o alvo e rejeita os dois quase-casos.

In [8]:
print("** REGRA 2 — caso positivo esperado: OP-0013 (USD 12.000 -> R$ 64.800) **")
cli_a4 = df[df["cliente_id"] == "CLI-A-4"]
mediana_a4 = float(cli_a4["valor_brl"].median())
limite = 5 * mediana_a4
flag_op13 = bool(df.loc[df["id"] == "OP-0013", "flag_valor_atipico"].iloc[0])
print(f"    Mediana do CLI-A-4: R$ {mediana_a4:,.2f} | Limite (5x): R$ {limite:,.2f}")
print(f"    OP-0013 sinalizada? {flag_op13}  (esperado: True)")
assert flag_op13

print("\n-- Contrafactual: se a regra rodasse ANTES da conversão USD->BRL --")
valores_secos = cli_a4["valor"]           # mistura BRL e USD 'secos'
limite_seco = 5 * float(valores_secos.median())
valor_seco_op13 = float(df.loc[df["id"] == "OP-0013", "valor"].iloc[0])
print(f"    Limite com moedas misturadas: R$ {limite_seco:,.2f}; OP-0013 'seca' = {valor_seco_op13:,.2f}",
      "-> NÃO seria sinalizada. A ordem das etapas muda o resultado.")
assert valor_seco_op13 <= limite_seco

print("\n-- Salvaguarda: clientes com < 4 operações jamais recebem flag --")
inelegiveis = df.groupby("cliente_id")["valor_brl"].size().loc[lambda s: s < 4].index.tolist()
assert not df[df["cliente_id"].isin(inelegiveis)]["flag_valor_atipico"].any()
print(f"    Clientes inelegíveis: {inelegiveis} — zero flags. Regra 2 validada.")

** REGRA 2 — caso positivo esperado: OP-0013 (USD 12.000 -> R$ 64.800) **
    Mediana do CLI-A-4: R$ 5,450.00 | Limite (5x): R$ 27,250.00
    OP-0013 sinalizada? True  (esperado: True)

-- Contrafactual: se a regra rodasse ANTES da conversão USD->BRL --
    Limite com moedas misturadas: R$ 27,250.00; OP-0013 'seca' = 12,000.00 -> NÃO seria sinalizada. A ordem das etapas muda o resultado.

-- Salvaguarda: clientes com < 4 operações jamais recebem flag --
    Clientes inelegíveis: ['CLI-A-2', 'CLI-A-3', 'CLI-A-6'] — zero flags. Regra 2 validada.

## Parte B — Parecer com LLM

**Cliente escolhido: CLI-A-1** — único com padrão clássico de fracionamento na base
(3 envios no mesmo dia, soma acima do limite, nenhum valor isolado relevante).
É um bom teste de **interpretação**: os números já estão prontos; cabe ao modelo ler o padrão.

Arquitetura da chamada:
1. Fatos calculados **em pandas** são injetados no prompt (o modelo não faz conta — critério que vale pontos);
2. Saída validada contra o schema `ParecerLLM` (pydantic);
3. Resposta malformada dispara **retry com instrução corretiva**;
4. Cache-first: respostas anteriores são reutilizadas (cotasy gratuitas limitam requisições);
5. Tokens e latência registrados em toda chamada.

> Nota: as respostas desta execução vêm do cache `../llm_cache/`, pré-geradas com
> assistente de IA durante o desenvolvimento por falta de quota de API — ver
> `docs/USO_DE_IA.md`. Com uma chave configurada no `.env`, a mesma célula chama
> Gemini/Groq/OpenRouter/Ollama sem nenhuma mudança de código.

In [9]:
class ParecerLLM(BaseModel):
    """Contrato de saída obrigatório do parecer."""
    nivel_risco: Literal["baixo", "médio", "alto"]
    tipologia_suspeita: str = Field(min_length=3)
    red_flags: list[str]
    justificativa: str = Field(min_length=10)

    @field_validator("nivel_risco", mode="before")
    @classmethod
    def _normalizar(cls, v):
        v = str(v).strip().lower()
        return {"medio": "médio"}.get(v, v)   # tolera 'ALTO', 'Medio' etc.


def extrair_json(texto: str) -> str:
    """Recupera o primeiro objeto JSON balanceado dentro da resposta do modelo."""
    ini = texto.find("{")
    if ini == -1:
        raise ValueError("nenhum objeto JSON na resposta")
    profundidade = 0
    for i, ch in enumerate(texto[ini:], start=ini):
        profundidade += (ch == "{") - (ch == "}")
        if profundidade == 0:
            return texto[ini : i + 1]
    raise ValueError("JSON não balanceado na resposta")


PASTA_CACHE = Path("../llm_cache")


def chamar_llm(case_key: str, system: str, user: str, temperatura: float = 0.2):
    """Chamada LLM com cache-first; sem cache, usa API real (SDK OpenAI-compatível)."""
    t0 = time.perf_counter()
    arquivo = PASTA_CACHE / f"{case_key}.json"
    if arquivo.exists():
        registro = json.loads(arquivo.read_text(encoding="utf-8"))
        origem = f"cache[{registro['origem']}]"
    else:
        registro = _chamada_api_real(system, user, temperatura)
        arquivo.write_text(json.dumps(registro, ensure_ascii=False, indent=2), encoding="utf-8")
        origem = "api"
    metrica = {
        "origem": origem,
        "tokens_prompt": registro.get("usage", {}).get("prompt_tokens"),
        "tokens_resposta": registro.get("usage", {}).get("completion_tokens"),
        "latencia_ms": round((time.perf_counter() - t0) * 1000),
    }
    return registro["response_text"], metrica


def _chamada_api_real(system: str, user: str, temperatura: float):
    import os

    from dotenv import load_dotenv

    load_dotenv(Path("..") / ".env")
    from openai import OpenAI

    provedor = os.getenv("LLM_PROVIDER", "").lower()
    endpoints = {
        "groq": ("https://api.groq.com/openai/v1", "GROQ_API_KEY"),
        "gemini": ("https://generativelanguage.googleapis.com/v1beta/openai/", "GOOGLE_API_KEY"),
        "openrouter": ("https://openrouter.ai/api/v1", "OPENROUTER_API_KEY"),
        "ollama": (os.getenv("OLLAMA_BASE_URL", "http://localhost:11434/v1"), None),
    }
    if provedor not in endpoints:
        raise RuntimeError(
            f"Sem cache para esta chamada e provedor '{provedor}' não configurado. "
            "Copie .env.example para .env e preencha uma chave gratuita."
        )
    base_url, var_chave = endpoints[provedor]
    chave = os.getenv(var_chave) if var_chave else "local"
    if var_chave and not chave:
        raise RuntimeError(f"Variável {var_chave} ausente no .env.")
    cliente = OpenAI(base_url=base_url, api_key=chave)
    resp = cliente.chat.completions.create(
        model=os.getenv("LLM_MODEL", "llama-3.3-70b-versatile"),
        temperature=temperatura,
        messages=[{"role": "system", "content": system}, {"role": "user", "content": user}],
    )
    return {
        "model": os.getenv("LLM_MODEL"),
        "system": system,
        "user": user,
        "response_text": resp.choices[0].message.content,
        "usage": {
            "prompt_tokens": getattr(resp.usage, "prompt_tokens", None),
            "completion_tokens": getattr(resp.usage, "completion_tokens", None),
        },
        "latency_ms": None,
        "origem": "api",
    }

In [10]:
SYSTEM = 'Você é analista sênior de prevenção à lavagem de dinheiro de um banco. Sua função é INTERPRETAR fatos já calculados pelo sistema e produzir um parecer técnico de triagem. Nunca realize cálculos; use exclusivamente os números fornecidos.'

FATOS = 'DADOS JÁ CALCULADOS PELO SISTEMA (não recalcule):\n- Cliente CLI-A-1: 4 operações em março/2026, volume total R$ 54.500,00.\n- Dia 2026-03-09: 3 transferências ENVIADAS somando R$ 54.200,00\n  (pix R$ 18.100,00; pix R$ 17.300,00; ted R$ 18.800,00).\n- Duas delas destinadas à mesma contraparte (Alfa Comercio LTDA).\n- Nenhuma operação do cliente atinge R$ 20.000,00 individualmente.\n- Parâmetro interno de fracionamento: >= 3 operacoes no mesmo dia,\n  soma > R$ 50.000,00 e nenhuma operacao isolada >= R$ 20.000,00.'

PROMPT_V1 = 'DADOS JÁ CALCULADOS PELO SISTEMA (não recalcule):\n- Cliente CLI-A-1: 4 operações em março/2026, volume total R$ 54.500,00.\n- Dia 2026-03-09: 3 transferências ENVIADAS somando R$ 54.200,00\n  (pix R$ 18.100,00; pix R$ 17.300,00; ted R$ 18.800,00).\n- Duas delas destinadas à mesma contraparte (Alfa Comercio LTDA).\n- Nenhuma operação do cliente atinge R$ 20.000,00 individualmente.\n- Parâmetro interno de fracionamento: >= 3 operacoes no mesmo dia,\n  soma > R$ 50.000,00 e nenhuma operacao isolada >= R$ 20.000,00.\n\nAnalise o cliente acima e me diga: ele parece suspeito? Qual o risco?'

print("--- PROMPT v1 (pergunta aberta) ---")
print(PROMPT_V1)

--- PROMPT v1 (pergunta aberta) ---
DADOS JÁ CALCULADOS PELO SISTEMA (não recalcule):
- Cliente CLI-A-1: 4 operações em março/2026, volume total R$ 54.500,00.
- Dia 2026-03-09: 3 transferências ENVIADAS somando R$ 54.200,00
  (pix R$ 18.100,00; pix R$ 17.300,00; ted R$ 18.800,00).
- Duas delas destinadas à mesma contraparte (Alfa Comercio LTDA).
- Nenhuma operação do cliente atinge R$ 20.000,00 individualmente.
- Parâmetro interno de fracionamento: >= 3 operacoes no mesmo dia,
  soma > R$ 50.000,00 e nenhuma operacao isolada >= R$ 20.000,00.

Analise o cliente acima e me diga: ele parece suspeito? Qual o risco?

In [11]:
texto_v1, met_v1 = chamar_llm("nivel1_cli_a_1_v1", SYSTEM, PROMPT_V1)
print("--- RESPOSTA v1 ---")
print(texto_v1)
try:
    ParecerLLM.model_validate_json(extrair_json(texto_v1))
    print("\nParse: OK")
except (ValidationError, ValueError) as erro:
    print(f"\n>>> Validacao estrutural FALHOU ({type(erro).__name__}): a resposta veio em prosa, fora do contrato.")

--- RESPOSTA v1 ---

Com base nos dados apresentados, sim — o comportamento do cliente CLI-A-1 apresenta indícios relevantes de fracionamento de valores.

Pontos que chamam atenção:
- Três transferências enviadas no mesmo dia (09/03/2026), somando R$ 54.200,00;
- Todas com valores imediatamente abaixo do patamar de R$ 20.000,00 (maior delas: R$ 18.800,00);
- Duas destinadas à mesma contraparte (Alfa Comercio LTDA), o que sugere destino comum dos recursos;
- O conjunto atende integralmente ao parâmetro interno (>= 3 operações/dia, soma > R$ 50.000,00, nenhuma isolada >= R$ 20.000,00).

Minha avaliação é de risco ALTO, com tipologia compatível com fracionamento (estruturação de valores). Recomendo encaminhar o caso para análise humana e verificar se o padrão se repete em outros períodos.

>>> Validacao estrutural FALHOU (ValueError): a resposta veio em prosa, fora do contrato.

In [12]:
CORRECAO = '\n\nSua resposta anterior nao seguiu o formato exigido. Responda novamente APENAS com um objeto JSON valido, sem nenhum texto ao redor, com as chaves: nivel_risco ("baixo"|"medio"|"alto"), tipologia_suspeita (string), red_flags (lista de strings) e justificativa (string).'

texto_v1r, met_v1r = chamar_llm("nivel1_cli_a_1_v1_retry", SYSTEM, PROMPT_V1 + CORRECAO)
parecer_v1 = ParecerLLM.model_validate_json(extrair_json(texto_v1r))
print("--- PARECER v1 (apos retry corretivo) ---")
parecer_v1.model_dump()

--- PARECER v1 (apos retry corretivo) ---

{'nivel_risco': 'alto',
 'tipologia_suspeita': 'fracionamento de valores (estruturação/smurfing)',
 'red_flags': ['Três transferências enviadas no mesmo dia (2026-03-09) somando R$ 54.200,00',
  'Valores individuais entre R$ 17.300,00 e R$ 18.800,00, todos abaixo de R$ 20.000,00',
  'Duas transferências para a mesma contraparte (Alfa Comercio LTDA)',
  'Padrão que atende integralmente ao parâmetro interno de fracionamento'],
 'justificativa': 'O dia 2026-03-09 concentra três envios que somados superam R$ 50.000,00 sem que qualquer operação isolada alcance R$ 20.000,00 — configuração típica de fracionamento para evitar gatilhos regulatórios. A repetição de contraparte reforça a hipótese de destinação única dos recursos. Recomendo elevar o caso à análise humana.'}

In [13]:
PROMPT_V2 = 'DADOS JÁ CALCULADOS PELO SISTEMA (não recalcule):\n- Cliente CLI-A-1: 4 operações em março/2026, volume total R$ 54.500,00.\n- Dia 2026-03-09: 3 transferências ENVIADAS somando R$ 54.200,00\n  (pix R$ 18.100,00; pix R$ 17.300,00; ted R$ 18.800,00).\n- Duas delas destinadas à mesma contraparte (Alfa Comercio LTDA).\n- Nenhuma operação do cliente atinge R$ 20.000,00 individualmente.\n- Parâmetro interno de fracionamento: >= 3 operacoes no mesmo dia,\n  soma > R$ 50.000,00 e nenhuma operacao isolada >= R$ 20.000,00.\n\nTAREFA: emitir um parecer de triagem em JSON VALIDO e nada alem dele.\nFormato exato: {"nivel_risco": "baixo"|"medio"|"alto",\n  "tipologia_suspeita": "<tipologia de PLD, ex.: fracionamento>",\n  "red_flags": ["<fato observado>", ...],\n  "justificativa": "<2-4 frases tecnicas citando os numeros fornecidos>"}\nCriterios de risco: ALTO exige padrao objetivo ja configurado nos fatos; MEDIO exige apenas indicios sem confirmacao; BAIXO, cenario plausivelmente explicavel.'

texto_v2, met_v2 = chamar_llm("nivel1_cli_a_1_v2", SYSTEM, PROMPT_V2)
parecer_v2 = ParecerLLM.model_validate_json(extrair_json(texto_v2))
print("--- PARECER v2 (contrato explicito desde a 1ª chamada) ---")
parecer_v2.model_dump()

--- PARECER v2 (contrato explicito desde a 1ª chamada) ---

{'nivel_risco': 'alto',
 'tipologia_suspeita': 'fracionamento de valores (estruturação)',
 'red_flags': ['3 transferências enviadas no mesmo dia somando R$ 54.200,00 (> R$ 50.000,00)',
  'Nenhuma operação isolada atinge R$ 20.000,00 (maior: R$ 18.800,00)',
  'Dois dos três envios concentrados na mesma contraparte (Alfa Comercio LTDA)'],
 'justificativa': 'Os fatos configuram integralmente o parâmetro interno de fracionamento: três envios no mesmo dia, soma de R$ 54.200,00 e valores individuais abaixo de R$ 20.000,00. O uso simultâneo de pix e ted não descaracteriza o padrão, pois o critério é diário e agregado. Caso recomendado para análise humana prioritária.'}

In [14]:
# Robustez: o pipeline aceita variações comuns de saída do modelo
demo_variacoes = [
    '{"nivel_risco": "ALTO", "tipologia_suspeita": "fracionamento", "red_flags": [], "justificativa": "padrao configurado nos fatos"}',
    'Claro! Segue a análise:\n```json\n' + json.dumps({
        "nivel_risco": "medio",
        "tipologia_suspeita": "indicios de fracionamento",
        "red_flags": ["operacoes proximas do limite"],
        "justificativa": "ha indicios, porem sem confirmacao plena"}) + "\n```",
]
for bruto_resp in demo_variacoes:
    parecer = ParecerLLM.model_validate_json(extrair_json(bruto_resp))
    print(f"normalizado -> nivel_risco='{parecer.nivel_risco}' (aceito)")

normalizado -> nivel_risco='alto' (aceito)
normalizado -> nivel_risco='médio' (aceito)

In [15]:
comparacao = pd.DataFrame([
    {
        "versao": "v1 — pergunta aberta",
        "chamadas": 2,
        "parse_ok_1a_tentativa": False,
        "tokens_prompt": (met_v1["tokens_prompt"] or 0) + (met_v1r["tokens_prompt"] or 0),
        "tokens_resposta": (met_v1["tokens_resposta"] or 0) + (met_v1r["tokens_resposta"] or 0),
        "latencia_ms": met_v1["latencia_ms"] + met_v1r["latencia_ms"],
    },
    {
        "versao": "v2 — contrato JSON explícito",
        "chamadas": 1,
        "parse_ok_1a_tentativa": True,
        "tokens_prompt": met_v2["tokens_prompt"] or 0,
        "tokens_resposta": met_v2["tokens_resposta"] or 0,
        "latencia_ms": met_v2["latencia_ms"],
    },
])
print("Comparação de custo/latência (offline os contadores de token vêm nulos do cache;")
print("com API real eles são populados automaticamente — ver células de métrica acima).")
comparacao

Comparação de custo/latência (offline os contadores de token vêm nulos do cache;
com API real eles são populados automaticamente — ver células de métrica acima).

,versao,chamadas,parse_ok_1a_tentativa,tokens_prompt,tokens_resposta,latencia_ms
0,v1 — pergunta aberta,2,False,0,0,17
1,v2 — contrato JSON explícito,1,True,0,0,8

### Leitura da comparação v1 × v2

- **v1 (aberta)** gerou resposta útil em conteúdo, porém em **prosa livre** — violou o
  contrato e custou uma **segunda chamada** (retry corretivo). Em produção, isso dobra
  latência e consumo de quota para todo caso.
- **v2 (contrato explícito)** entregou JSON válido **de primeira**, com `red_flags`
  objetivas ancoradas nos números fornecidos — sem custo extra de parsing defensivo.
- Conclusão adotada no projeto: prompts de produção usam sempre o estilo v2
  (contrato + critérios de risco + proibição de calcular), e o retry corretivo
  permanece como rede de segurança.

### Conclusões do Nível 1

1. A base legado trouxe 3 problemas plantados (duplicata, data nula, USD) — todos
   tratados com decisão documentada; a ordem **converter → agregar → regrar** provou-se essencial.
2. A Regra 1 captura CLI-A-1 e rejeita os dois quase-casos (CLI-A-3 só passa por causa
   da limpeza; CLI-A-2 falha em dois critérios simultâneos).
3. A Regra 2 captura a remessa internacional de CLI-A-4 **somente** após a conversão BRL.
4. LLM bem instruído interpreta; mal instruído, obriga retrabalho — contrato explícito
   economiza chamadas.